CWE23_Relative_Path_Traversal__char_environment_fopen_14: CWE23_Relative_Path_Traversal__char_environment_fopen_14.cpp
	g++ -o CWE23_Relative_Path_Traversal__char_environment_fopen_14 CWE23_Relative_Path_Traversal__char_environment_fopen_14.cpp

